apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wabbf65nt-python 
  janus-idp.io/tekton: wabbf65nt-python
  backstage.io/kubernetes-id: wabbf65nt-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wabbf65nt-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml