apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wabbf65nt-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wabbf65nt-python 
  name: wabbf65nt-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wabbf65nt-python 
